kind: pipeline
type: docker
name: im-static-build

steps:
  - name: build
    image: golang
    environment:
      GOPROXY: https://goproxy.cn,direct
      GOPRIVATE: github.com/zengyu2020
      GOPATH: /go
    volumes:
      - name: gopath
        path: /go
    commands:
      - go build -o im-static main.go
    when:
      branch:
        - master
  - name: deploy docker image
    image: plugins/docker
    volumes:
      - name: external-docker
        path: /var/run/docker.sock
    commands:
      - ls -a
      - docker rm -f im-static-v1 || echo "no such images."
      - docker container  rm -im-static-v1 || echo "no such images."
      - docker rmi im-static-v1:1.0 || echo "no such images."
      - docker build -t im-static-v1:1.0 .
      - docker run -d -p 8091:8091 im-static-v1:1.0

volumes:
  - name: gopath
    host:
      path: /data/gopath
  - name: external-docker
    host:
      path: /var/run/docker.sock
