name: im-static

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: deploy docker image
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        WELCOME: "ssh scp ssh pipelines"
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.CI_HOST }}
        user: ${{ secrets.CI_USERNAME }}
        key: ${{ secrets.CI_KEY }}
        port: 22
        connect_timeout: 10s
        first_ssh: |
          
        scp: ./im-static-1.0.tar => /data/docker/images/
        last_ssh: |
          cd /data/docker/images
          docker load --input im-static-1.0.tar
          docker run -d -P im-static:1.0
