name: im-static

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    # - name: deploy docker image
    #   uses: cross-the-world/ssh-scp-ssh-pipelines@latest
    #   env:
    #     WELCOME: "ssh scp ssh pipelines"
    #     LASTSSH: "Doing something after copying"
    #   with:
    #     host: ${{ secrets.CI_HOST }}
    #     user: ${{ secrets.CI_USERNAME }}
    #     key: ${{ secrets.CI_KEY }}
    #     port: 22
    #     connect_timeout: 10s
    #     scp: |
    #       ./* => /data/im/im-static-v1/
    #     last_ssh: |
    #       cd /data/im/im-static-v1
    #       docker -t im-static:v1 .
    #       docker run -d -P im-static:1.0
    - name: scp code
      uses: cross-the-world/scp-pipeline@master
      with:
        host: ${{ secrets.CI_HOST }}
        user: ${{ secrets.CI_USERNAME }}
        pass: ${{ secrets.CI_PASS }}
        port: 22
        connect_timeout: 10s
        scp: |
          ./* => /data/im/im-static-v1/
    - name: deploy docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CI_HOST }}
        username: ${{ secrets.CI_USERNAME }}
        key: ${{ secrets.CI_KEY }}
        port: 22
        script: |
          cd /data/im/im-static-v1
          docker -t im-static:v1 .
          docker run -d -P im-static:1.0